### ISSUE TITLE
Compile error after updating to 0.2.4

### ISSUE THREAD

**Issue by christophermichaelshaw** [lhns/docker-swarm-keepalived#7]
I received the below errors after updating to the recent 0.2.4 update. Works when I revert to 0.2.3.

Thanks for taking a look at this -- Let me know if I can provide any further logs or information to assist in troubleshooting! 

```
[root@docker-node1 keepalived]# docker stack deploy keepalived --compose-file docker-compose.yml 
Updating service keepalived_keepalived (id: e8ca0ogd0uvcychqoc4iv86jz)
[root@docker-node1 keepalived]# docker service logs --follow keepalived_keepalived 
keepalived_keepalived.0.pgf26ltyzfux@docker-node1    | jq: error: Top-level program not given (try ".")
keepalived_keepalived.0.ucsk8nqq5x8u@docker-node1    | jq: error: Top-level program not given (try ".")
keepalived_keepalived.0.pgf26ltyzfux@docker-node1    | jq: 1 compile error
keepalived_keepalived.0.ucsk8nqq5x8u@docker-node1  | jq: 1 compile error
keepalived_keepalived.0.jrog4ek6ufz8@docker-node1    | jq: error: Top-level program not given (try ".")
```

Here's my config file:
```
version: '3.8'

services:
  keepalived:
    image: lolhens/keepalived-swarm:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker:ro
    networks:
      - host
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]
    environment:
      KEEPALIVED_VIRTUAL_IPS: "[IP_ADDRESS]"

networks:
  host:
    external: true
    name: host
```
